// app/layout.js or app/layout.tsx (based on your structure)
import "./globals.css";
// import logo from "../../../public/logo.svg";
import logo from "../../public/logo.svg";

export const metadata = {
  title: "jyothishwar portfolio",
  icons: {
    icon: logo,
    shortcut: logo,
    apple: logo,
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
